server:
  port: 8088
  servlet:
    context-path: /alert

spring:
  application:
    name: data-nest-alert

  config:
    import:
      - optional:nacos:shared-nacos.yaml?group=shared-configs&refreshEnabled=true
      - optional:nacos:shared-common.yaml?group=shared-configs&refreshEnabled=true
      - optional:nacos:shared-datasource.yaml?group=shared-configs&refreshEnabled=true
      - optional:nacos:shared-security.yaml?group=shared-configs&refreshEnabled=true
      - optional:nacos:shared-alert.yaml?group=shared-configs&refreshEnabled=true
      - optional:nacos:shared-internal.yaml?group=shared-configs&refreshEnabled=true

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
      config:
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        file-extension: yaml
