server:
  port: 8080

spring:
  application:
    name: data-nest-gateway

  config:
    import:
      - optional:nacos:shared-security.yaml?group=shared-configs&refreshEnabled=true

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
      config:
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
        file-extension: yaml

    gateway:
      server:
        webflux:
          routes:
            - id: system-service
              uri: lb://data-nest-system
              predicates:
                - Path=/api/system/**
              filters:
                - StripPrefix=1

springdoc:
  api-docs:
    enabled: false
