server:
  port: 8080

spring:
  application:
    name: data-nest-gateway

  config:
    import:
      - optional:nacos:shared-nacos.yaml?group=shared-configs&refreshEnabled=true
      - optional:nacos:shared-common.yaml?group=shared-configs&refreshEnabled=true
      - optional:nacos:shared-security.yaml?group=shared-configs&refreshEnabled=true

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
      config:
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
        file-extension: yaml
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 3000
            response-timeout: 30s
            pool:
              type: elastic
              max-connections: 500
              max-life-time: 30s
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          routes:
            - id: system-service
              uri: lb://data-nest-system
              predicates:
                - Path=/api/system/**
              filters:
                - StripPrefix=1
            - id: engineering-service
              uri: lb://data-nest-engineering
              predicates:
                - Path=/api/engineering/**
              filters:
                - StripPrefix=1
            - id: governance-service
              uri: lb://data-nest-governance
              predicates:
                - Path=/api/governance/**
              filters:
                - StripPrefix=1
            - id: worker-service
              uri: lb://data-nest-worker
              predicates:
                - Path=/api/worker/**
              filters:
                - StripPrefix=1
            - id: alert-service
              uri: lb://data-nest-alert
              predicates:
                - Path=/api/alert/**
              filters:
                - StripPrefix=1
