-- ============================================
-- V1.1.3__seed_preset_roles_and_admin.sql
-- Sprint 12 补：预置 4 角色 + admin 账号 + 角色权限矩阵（全新部署种子）
-- 背景：V1.0.0 baseline 为 pg_dump --schema-only（无数据），V1.1.1 的角色权限 INSERT...SELECT
--       依赖 sys_role 已存在，全新库上静默 0 行，导致新环境无法登录。本脚本补齐种子并重放
--       矩阵（全部幂等：唯一键冲突 DO NOTHING）。
-- ============================================
INSERT INTO sys_role (id, code, name, description) VALUES (1, 'SUPER_ADMIN', '超级管理员', '拥有系统所有权限'), (2, 'DATA_ENGINEER', '数据工程师', '负责数据集成和数据开发'), (3, 'DATA_ANALYST', '数据分析师', '数据查询与分析'), (4, 'GOVERNANCE_ADMIN', '治理管理员', '数据治理与质量管理') ON CONFLICT DO NOTHING;
INSERT INTO sys_user (id, username, password, email, enabled) VALUES (1, 'admin', '$2b$12$5Hsog/ML5QbrAPivCqsCeuLJpItjSvMS7HPqtWwOy53DgX8mE1Deu', 'admin@datanest.io', TRUE) ON CONFLICT DO NOTHING;
INSERT INTO sys_user_role (id, user_id, role_id) VALUES (1, 1, 1) ON CONFLICT DO NOTHING;
-- 超级管理员：全部权限点
INSERT INTO sys_role_permission (id, role_id, permission_id, created_at) SELECT 1000000 + row_number() OVER (), r.id, p.id, CURRENT_TIMESTAMP FROM sys_role r CROSS JOIN sys_permission p WHERE r.code = 'SUPER_ADMIN' ON CONFLICT DO NOTHING;
-- 数据工程师（PRD §6.2.1 矩阵）
INSERT INTO sys_role_permission (id, role_id, permission_id, created_at) SELECT 2000000 + row_number() OVER (), r.id, p.id, CURRENT_TIMESTAMP FROM sys_role r CROSS JOIN sys_permission p WHERE r.code = 'DATA_ENGINEER' AND p.code IN ('datasource:view','datasource:create','datasource:update','datasource:delete','datasource:test','sync:view','sync:create','sync:update','sync:delete','sync:execute','sync:history','cdc:view','cdc:create','cdc:update','cdc:delete','cdc:execute','cdc:monitor','dag:view','dag:create','dag:update','dag:delete','dag:execute','dag:history','template:view','template:create','template:update','template:delete','metadata:view','metadata:comment','metadata:lineage','compliance:view','quality_result:score','quality_result:report','asset:view','asset:collab','asset:comment','sql:execute','sql:export','sql:history','api:view','api:create','api:update','api:publish','api:delete','api:stats','api_key:view','api_key:create','api_key:toggle','api_key:delete','sensitivity:view','alert:view','alert:rule_manage') ON CONFLICT DO NOTHING;
-- 数据分析师（PRD §6.2.1 矩阵）
INSERT INTO sys_role_permission (id, role_id, permission_id, created_at) SELECT 3000000 + row_number() OVER (), r.id, p.id, CURRENT_TIMESTAMP FROM sys_role r CROSS JOIN sys_permission p WHERE r.code = 'DATA_ANALYST' AND p.code IN ('cdc:view','cdc:monitor','dag:view','dag:history','metadata:view','quality_result:score','quality_result:report','asset:view','asset:collab','asset:comment','sql:execute','sql:export','sql:history','api:view','api:stats','api_key:view','sensitivity:view') ON CONFLICT DO NOTHING;
-- 治理管理员（PRD §6.2.1 矩阵）
INSERT INTO sys_role_permission (id, role_id, permission_id, created_at) SELECT 4000000 + row_number() OVER (), r.id, p.id, CURRENT_TIMESTAMP FROM sys_role r CROSS JOIN sys_permission p WHERE r.code = 'GOVERNANCE_ADMIN' AND p.code IN ('datasource:view','cdc:view','cdc:monitor','dag:view','dag:history','metadata:view','metadata:comment','metadata:lineage','collect:view','collect:create','collect:update','collect:delete','collect:execute','collect:history','standard:view','standard:create','standard:update','standard:delete','compliance:view','compliance:handle','quality_rule:view','quality_rule:create','quality_rule:update','quality_rule:delete','quality_job:view','quality_job:create','quality_job:update','quality_job:delete','quality_job:execute','quality_job:history','quality_result:score','quality_result:report','asset:view','asset:collab','asset:comment','asset:manage','api:view','api:stats','api_key:view','sensitivity:view','sensitivity:change','sensitivity:batch_change','alert:view') ON CONFLICT DO NOTHING;
